name: Publish

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: [Build & Package]
    types:
      - completed

jobs:
  publish:
    if: startsWith(github.event.workflow_run.head_branch, 'refs/tags/')
    name: Publish Executables
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: 'Produkte Generator (Windows)'
        path: 'artifacts'
    - uses: actions/download-artifact@v2
      with:
        name: 'Produkte Generator (Linux)'
        path: 'artifacts'

    - name: Upload artifacts to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: artifacts/*
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
